
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PacientePrevenda` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PacientePrevenda
 * 
 */
export type PacientePrevendaModel = runtime.Types.Result.DefaultSelection<Prisma.$PacientePrevendaPayload>

export type AggregatePacientePrevenda = {
  _count: PacientePrevendaCountAggregateOutputType | null
  _avg: PacientePrevendaAvgAggregateOutputType | null
  _sum: PacientePrevendaSumAggregateOutputType | null
  _min: PacientePrevendaMinAggregateOutputType | null
  _max: PacientePrevendaMaxAggregateOutputType | null
}

export type PacientePrevendaAvgAggregateOutputType = {
  id: number | null
}

export type PacientePrevendaSumAggregateOutputType = {
  id: number | null
}

export type PacientePrevendaMinAggregateOutputType = {
  id: number | null
  nome: string | null
  telefone: string | null
  mensagem: string | null
  genero: string | null
  idade: string | null
  desafio: string | null
  energia: string | null
  compromisso: string | null
  sessionId: string | null
  quizStartedAt: Date | null
  quizCompletedAt: Date | null
  userAgent: string | null
  origem: string | null
  pagina: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PacientePrevendaMaxAggregateOutputType = {
  id: number | null
  nome: string | null
  telefone: string | null
  mensagem: string | null
  genero: string | null
  idade: string | null
  desafio: string | null
  energia: string | null
  compromisso: string | null
  sessionId: string | null
  quizStartedAt: Date | null
  quizCompletedAt: Date | null
  userAgent: string | null
  origem: string | null
  pagina: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PacientePrevendaCountAggregateOutputType = {
  id: number
  nome: number
  telefone: number
  mensagem: number
  genero: number
  idade: number
  desafio: number
  energia: number
  compromisso: number
  sessionId: number
  quizStartedAt: number
  quizCompletedAt: number
  userAgent: number
  origem: number
  pagina: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PacientePrevendaAvgAggregateInputType = {
  id?: true
}

export type PacientePrevendaSumAggregateInputType = {
  id?: true
}

export type PacientePrevendaMinAggregateInputType = {
  id?: true
  nome?: true
  telefone?: true
  mensagem?: true
  genero?: true
  idade?: true
  desafio?: true
  energia?: true
  compromisso?: true
  sessionId?: true
  quizStartedAt?: true
  quizCompletedAt?: true
  userAgent?: true
  origem?: true
  pagina?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PacientePrevendaMaxAggregateInputType = {
  id?: true
  nome?: true
  telefone?: true
  mensagem?: true
  genero?: true
  idade?: true
  desafio?: true
  energia?: true
  compromisso?: true
  sessionId?: true
  quizStartedAt?: true
  quizCompletedAt?: true
  userAgent?: true
  origem?: true
  pagina?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PacientePrevendaCountAggregateInputType = {
  id?: true
  nome?: true
  telefone?: true
  mensagem?: true
  genero?: true
  idade?: true
  desafio?: true
  energia?: true
  compromisso?: true
  sessionId?: true
  quizStartedAt?: true
  quizCompletedAt?: true
  userAgent?: true
  origem?: true
  pagina?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PacientePrevendaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PacientePrevenda to aggregate.
   */
  where?: Prisma.PacientePrevendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacientePrevendas to fetch.
   */
  orderBy?: Prisma.PacientePrevendaOrderByWithRelationInput | Prisma.PacientePrevendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PacientePrevendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacientePrevendas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacientePrevendas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PacientePrevendas
  **/
  _count?: true | PacientePrevendaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PacientePrevendaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PacientePrevendaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PacientePrevendaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PacientePrevendaMaxAggregateInputType
}

export type GetPacientePrevendaAggregateType<T extends PacientePrevendaAggregateArgs> = {
      [P in keyof T & keyof AggregatePacientePrevenda]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePacientePrevenda[P]>
    : Prisma.GetScalarType<T[P], AggregatePacientePrevenda[P]>
}




export type PacientePrevendaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PacientePrevendaWhereInput
  orderBy?: Prisma.PacientePrevendaOrderByWithAggregationInput | Prisma.PacientePrevendaOrderByWithAggregationInput[]
  by: Prisma.PacientePrevendaScalarFieldEnum[] | Prisma.PacientePrevendaScalarFieldEnum
  having?: Prisma.PacientePrevendaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PacientePrevendaCountAggregateInputType | true
  _avg?: PacientePrevendaAvgAggregateInputType
  _sum?: PacientePrevendaSumAggregateInputType
  _min?: PacientePrevendaMinAggregateInputType
  _max?: PacientePrevendaMaxAggregateInputType
}

export type PacientePrevendaGroupByOutputType = {
  id: number
  nome: string
  telefone: string
  mensagem: string | null
  genero: string
  idade: string
  desafio: string
  energia: string
  compromisso: string
  sessionId: string | null
  quizStartedAt: Date | null
  quizCompletedAt: Date | null
  userAgent: string | null
  origem: string | null
  pagina: string
  status: string
  createdAt: Date
  updatedAt: Date
  _count: PacientePrevendaCountAggregateOutputType | null
  _avg: PacientePrevendaAvgAggregateOutputType | null
  _sum: PacientePrevendaSumAggregateOutputType | null
  _min: PacientePrevendaMinAggregateOutputType | null
  _max: PacientePrevendaMaxAggregateOutputType | null
}

export type GetPacientePrevendaGroupByPayload<T extends PacientePrevendaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PacientePrevendaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PacientePrevendaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PacientePrevendaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PacientePrevendaGroupByOutputType[P]>
      }
    >
  >



export type PacientePrevendaWhereInput = {
  AND?: Prisma.PacientePrevendaWhereInput | Prisma.PacientePrevendaWhereInput[]
  OR?: Prisma.PacientePrevendaWhereInput[]
  NOT?: Prisma.PacientePrevendaWhereInput | Prisma.PacientePrevendaWhereInput[]
  id?: Prisma.IntFilter<"PacientePrevenda"> | number
  nome?: Prisma.StringFilter<"PacientePrevenda"> | string
  telefone?: Prisma.StringFilter<"PacientePrevenda"> | string
  mensagem?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  genero?: Prisma.StringFilter<"PacientePrevenda"> | string
  idade?: Prisma.StringFilter<"PacientePrevenda"> | string
  desafio?: Prisma.StringFilter<"PacientePrevenda"> | string
  energia?: Prisma.StringFilter<"PacientePrevenda"> | string
  compromisso?: Prisma.StringFilter<"PacientePrevenda"> | string
  sessionId?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  quizStartedAt?: Prisma.DateTimeNullableFilter<"PacientePrevenda"> | Date | string | null
  quizCompletedAt?: Prisma.DateTimeNullableFilter<"PacientePrevenda"> | Date | string | null
  userAgent?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  origem?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  pagina?: Prisma.StringFilter<"PacientePrevenda"> | string
  status?: Prisma.StringFilter<"PacientePrevenda"> | string
  createdAt?: Prisma.DateTimeFilter<"PacientePrevenda"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PacientePrevenda"> | Date | string
}

export type PacientePrevendaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  mensagem?: Prisma.SortOrderInput | Prisma.SortOrder
  genero?: Prisma.SortOrder
  idade?: Prisma.SortOrder
  desafio?: Prisma.SortOrder
  energia?: Prisma.SortOrder
  compromisso?: Prisma.SortOrder
  sessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  origem?: Prisma.SortOrderInput | Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacientePrevendaWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PacientePrevendaWhereInput | Prisma.PacientePrevendaWhereInput[]
  OR?: Prisma.PacientePrevendaWhereInput[]
  NOT?: Prisma.PacientePrevendaWhereInput | Prisma.PacientePrevendaWhereInput[]
  nome?: Prisma.StringFilter<"PacientePrevenda"> | string
  telefone?: Prisma.StringFilter<"PacientePrevenda"> | string
  mensagem?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  genero?: Prisma.StringFilter<"PacientePrevenda"> | string
  idade?: Prisma.StringFilter<"PacientePrevenda"> | string
  desafio?: Prisma.StringFilter<"PacientePrevenda"> | string
  energia?: Prisma.StringFilter<"PacientePrevenda"> | string
  compromisso?: Prisma.StringFilter<"PacientePrevenda"> | string
  sessionId?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  quizStartedAt?: Prisma.DateTimeNullableFilter<"PacientePrevenda"> | Date | string | null
  quizCompletedAt?: Prisma.DateTimeNullableFilter<"PacientePrevenda"> | Date | string | null
  userAgent?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  origem?: Prisma.StringNullableFilter<"PacientePrevenda"> | string | null
  pagina?: Prisma.StringFilter<"PacientePrevenda"> | string
  status?: Prisma.StringFilter<"PacientePrevenda"> | string
  createdAt?: Prisma.DateTimeFilter<"PacientePrevenda"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PacientePrevenda"> | Date | string
}, "id">

export type PacientePrevendaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  mensagem?: Prisma.SortOrderInput | Prisma.SortOrder
  genero?: Prisma.SortOrder
  idade?: Prisma.SortOrder
  desafio?: Prisma.SortOrder
  energia?: Prisma.SortOrder
  compromisso?: Prisma.SortOrder
  sessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  origem?: Prisma.SortOrderInput | Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PacientePrevendaCountOrderByAggregateInput
  _avg?: Prisma.PacientePrevendaAvgOrderByAggregateInput
  _max?: Prisma.PacientePrevendaMaxOrderByAggregateInput
  _min?: Prisma.PacientePrevendaMinOrderByAggregateInput
  _sum?: Prisma.PacientePrevendaSumOrderByAggregateInput
}

export type PacientePrevendaScalarWhereWithAggregatesInput = {
  AND?: Prisma.PacientePrevendaScalarWhereWithAggregatesInput | Prisma.PacientePrevendaScalarWhereWithAggregatesInput[]
  OR?: Prisma.PacientePrevendaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PacientePrevendaScalarWhereWithAggregatesInput | Prisma.PacientePrevendaScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PacientePrevenda"> | number
  nome?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  telefone?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  mensagem?: Prisma.StringNullableWithAggregatesFilter<"PacientePrevenda"> | string | null
  genero?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  idade?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  desafio?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  energia?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  compromisso?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  sessionId?: Prisma.StringNullableWithAggregatesFilter<"PacientePrevenda"> | string | null
  quizStartedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PacientePrevenda"> | Date | string | null
  quizCompletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PacientePrevenda"> | Date | string | null
  userAgent?: Prisma.StringNullableWithAggregatesFilter<"PacientePrevenda"> | string | null
  origem?: Prisma.StringNullableWithAggregatesFilter<"PacientePrevenda"> | string | null
  pagina?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  status?: Prisma.StringWithAggregatesFilter<"PacientePrevenda"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PacientePrevenda"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PacientePrevenda"> | Date | string
}

export type PacientePrevendaCreateInput = {
  nome: string
  telefone: string
  mensagem?: string | null
  genero: string
  idade: string
  desafio: string
  energia: string
  compromisso: string
  sessionId?: string | null
  quizStartedAt?: Date | string | null
  quizCompletedAt?: Date | string | null
  userAgent?: string | null
  origem?: string | null
  pagina?: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PacientePrevendaUncheckedCreateInput = {
  id?: number
  nome: string
  telefone: string
  mensagem?: string | null
  genero: string
  idade: string
  desafio: string
  energia: string
  compromisso: string
  sessionId?: string | null
  quizStartedAt?: Date | string | null
  quizCompletedAt?: Date | string | null
  userAgent?: string | null
  origem?: string | null
  pagina?: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PacientePrevendaUpdateInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  genero?: Prisma.StringFieldUpdateOperationsInput | string
  idade?: Prisma.StringFieldUpdateOperationsInput | string
  desafio?: Prisma.StringFieldUpdateOperationsInput | string
  energia?: Prisma.StringFieldUpdateOperationsInput | string
  compromisso?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacientePrevendaUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  genero?: Prisma.StringFieldUpdateOperationsInput | string
  idade?: Prisma.StringFieldUpdateOperationsInput | string
  desafio?: Prisma.StringFieldUpdateOperationsInput | string
  energia?: Prisma.StringFieldUpdateOperationsInput | string
  compromisso?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacientePrevendaCreateManyInput = {
  id?: number
  nome: string
  telefone: string
  mensagem?: string | null
  genero: string
  idade: string
  desafio: string
  energia: string
  compromisso: string
  sessionId?: string | null
  quizStartedAt?: Date | string | null
  quizCompletedAt?: Date | string | null
  userAgent?: string | null
  origem?: string | null
  pagina?: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PacientePrevendaUpdateManyMutationInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  genero?: Prisma.StringFieldUpdateOperationsInput | string
  idade?: Prisma.StringFieldUpdateOperationsInput | string
  desafio?: Prisma.StringFieldUpdateOperationsInput | string
  energia?: Prisma.StringFieldUpdateOperationsInput | string
  compromisso?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacientePrevendaUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  genero?: Prisma.StringFieldUpdateOperationsInput | string
  idade?: Prisma.StringFieldUpdateOperationsInput | string
  desafio?: Prisma.StringFieldUpdateOperationsInput | string
  energia?: Prisma.StringFieldUpdateOperationsInput | string
  compromisso?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacientePrevendaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  genero?: Prisma.SortOrder
  idade?: Prisma.SortOrder
  desafio?: Prisma.SortOrder
  energia?: Prisma.SortOrder
  compromisso?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origem?: Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacientePrevendaAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PacientePrevendaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  genero?: Prisma.SortOrder
  idade?: Prisma.SortOrder
  desafio?: Prisma.SortOrder
  energia?: Prisma.SortOrder
  compromisso?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origem?: Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacientePrevendaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  genero?: Prisma.SortOrder
  idade?: Prisma.SortOrder
  desafio?: Prisma.SortOrder
  energia?: Prisma.SortOrder
  compromisso?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origem?: Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacientePrevendaSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type PacientePrevendaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  telefone?: boolean
  mensagem?: boolean
  genero?: boolean
  idade?: boolean
  desafio?: boolean
  energia?: boolean
  compromisso?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["pacientePrevenda"]>

export type PacientePrevendaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  telefone?: boolean
  mensagem?: boolean
  genero?: boolean
  idade?: boolean
  desafio?: boolean
  energia?: boolean
  compromisso?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["pacientePrevenda"]>

export type PacientePrevendaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  telefone?: boolean
  mensagem?: boolean
  genero?: boolean
  idade?: boolean
  desafio?: boolean
  energia?: boolean
  compromisso?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["pacientePrevenda"]>

export type PacientePrevendaSelectScalar = {
  id?: boolean
  nome?: boolean
  telefone?: boolean
  mensagem?: boolean
  genero?: boolean
  idade?: boolean
  desafio?: boolean
  energia?: boolean
  compromisso?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PacientePrevendaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "telefone" | "mensagem" | "genero" | "idade" | "desafio" | "energia" | "compromisso" | "sessionId" | "quizStartedAt" | "quizCompletedAt" | "userAgent" | "origem" | "pagina" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["pacientePrevenda"]>

export type $PacientePrevendaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PacientePrevenda"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nome: string
    telefone: string
    mensagem: string | null
    genero: string
    idade: string
    desafio: string
    energia: string
    compromisso: string
    sessionId: string | null
    quizStartedAt: Date | null
    quizCompletedAt: Date | null
    userAgent: string | null
    origem: string | null
    pagina: string
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pacientePrevenda"]>
  composites: {}
}

export type PacientePrevendaGetPayload<S extends boolean | null | undefined | PacientePrevendaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload, S>

export type PacientePrevendaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PacientePrevendaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PacientePrevendaCountAggregateInputType | true
  }

export interface PacientePrevendaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PacientePrevenda'], meta: { name: 'PacientePrevenda' } }
  /**
   * Find zero or one PacientePrevenda that matches the filter.
   * @param {PacientePrevendaFindUniqueArgs} args - Arguments to find a PacientePrevenda
   * @example
   * // Get one PacientePrevenda
   * const pacientePrevenda = await prisma.pacientePrevenda.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PacientePrevendaFindUniqueArgs>(args: Prisma.SelectSubset<T, PacientePrevendaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PacientePrevenda that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PacientePrevendaFindUniqueOrThrowArgs} args - Arguments to find a PacientePrevenda
   * @example
   * // Get one PacientePrevenda
   * const pacientePrevenda = await prisma.pacientePrevenda.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PacientePrevendaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PacientePrevendaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PacientePrevenda that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacientePrevendaFindFirstArgs} args - Arguments to find a PacientePrevenda
   * @example
   * // Get one PacientePrevenda
   * const pacientePrevenda = await prisma.pacientePrevenda.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PacientePrevendaFindFirstArgs>(args?: Prisma.SelectSubset<T, PacientePrevendaFindFirstArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PacientePrevenda that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacientePrevendaFindFirstOrThrowArgs} args - Arguments to find a PacientePrevenda
   * @example
   * // Get one PacientePrevenda
   * const pacientePrevenda = await prisma.pacientePrevenda.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PacientePrevendaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PacientePrevendaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PacientePrevendas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacientePrevendaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PacientePrevendas
   * const pacientePrevendas = await prisma.pacientePrevenda.findMany()
   * 
   * // Get first 10 PacientePrevendas
   * const pacientePrevendas = await prisma.pacientePrevenda.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pacientePrevendaWithIdOnly = await prisma.pacientePrevenda.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PacientePrevendaFindManyArgs>(args?: Prisma.SelectSubset<T, PacientePrevendaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PacientePrevenda.
   * @param {PacientePrevendaCreateArgs} args - Arguments to create a PacientePrevenda.
   * @example
   * // Create one PacientePrevenda
   * const PacientePrevenda = await prisma.pacientePrevenda.create({
   *   data: {
   *     // ... data to create a PacientePrevenda
   *   }
   * })
   * 
   */
  create<T extends PacientePrevendaCreateArgs>(args: Prisma.SelectSubset<T, PacientePrevendaCreateArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PacientePrevendas.
   * @param {PacientePrevendaCreateManyArgs} args - Arguments to create many PacientePrevendas.
   * @example
   * // Create many PacientePrevendas
   * const pacientePrevenda = await prisma.pacientePrevenda.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PacientePrevendaCreateManyArgs>(args?: Prisma.SelectSubset<T, PacientePrevendaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PacientePrevendas and returns the data saved in the database.
   * @param {PacientePrevendaCreateManyAndReturnArgs} args - Arguments to create many PacientePrevendas.
   * @example
   * // Create many PacientePrevendas
   * const pacientePrevenda = await prisma.pacientePrevenda.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PacientePrevendas and only return the `id`
   * const pacientePrevendaWithIdOnly = await prisma.pacientePrevenda.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PacientePrevendaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PacientePrevendaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PacientePrevenda.
   * @param {PacientePrevendaDeleteArgs} args - Arguments to delete one PacientePrevenda.
   * @example
   * // Delete one PacientePrevenda
   * const PacientePrevenda = await prisma.pacientePrevenda.delete({
   *   where: {
   *     // ... filter to delete one PacientePrevenda
   *   }
   * })
   * 
   */
  delete<T extends PacientePrevendaDeleteArgs>(args: Prisma.SelectSubset<T, PacientePrevendaDeleteArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PacientePrevenda.
   * @param {PacientePrevendaUpdateArgs} args - Arguments to update one PacientePrevenda.
   * @example
   * // Update one PacientePrevenda
   * const pacientePrevenda = await prisma.pacientePrevenda.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PacientePrevendaUpdateArgs>(args: Prisma.SelectSubset<T, PacientePrevendaUpdateArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PacientePrevendas.
   * @param {PacientePrevendaDeleteManyArgs} args - Arguments to filter PacientePrevendas to delete.
   * @example
   * // Delete a few PacientePrevendas
   * const { count } = await prisma.pacientePrevenda.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PacientePrevendaDeleteManyArgs>(args?: Prisma.SelectSubset<T, PacientePrevendaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PacientePrevendas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacientePrevendaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PacientePrevendas
   * const pacientePrevenda = await prisma.pacientePrevenda.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PacientePrevendaUpdateManyArgs>(args: Prisma.SelectSubset<T, PacientePrevendaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PacientePrevendas and returns the data updated in the database.
   * @param {PacientePrevendaUpdateManyAndReturnArgs} args - Arguments to update many PacientePrevendas.
   * @example
   * // Update many PacientePrevendas
   * const pacientePrevenda = await prisma.pacientePrevenda.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PacientePrevendas and only return the `id`
   * const pacientePrevendaWithIdOnly = await prisma.pacientePrevenda.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PacientePrevendaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PacientePrevendaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PacientePrevenda.
   * @param {PacientePrevendaUpsertArgs} args - Arguments to update or create a PacientePrevenda.
   * @example
   * // Update or create a PacientePrevenda
   * const pacientePrevenda = await prisma.pacientePrevenda.upsert({
   *   create: {
   *     // ... data to create a PacientePrevenda
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PacientePrevenda we want to update
   *   }
   * })
   */
  upsert<T extends PacientePrevendaUpsertArgs>(args: Prisma.SelectSubset<T, PacientePrevendaUpsertArgs<ExtArgs>>): Prisma.Prisma__PacientePrevendaClient<runtime.Types.Result.GetResult<Prisma.$PacientePrevendaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PacientePrevendas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacientePrevendaCountArgs} args - Arguments to filter PacientePrevendas to count.
   * @example
   * // Count the number of PacientePrevendas
   * const count = await prisma.pacientePrevenda.count({
   *   where: {
   *     // ... the filter for the PacientePrevendas we want to count
   *   }
   * })
  **/
  count<T extends PacientePrevendaCountArgs>(
    args?: Prisma.Subset<T, PacientePrevendaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PacientePrevendaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PacientePrevenda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacientePrevendaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PacientePrevendaAggregateArgs>(args: Prisma.Subset<T, PacientePrevendaAggregateArgs>): Prisma.PrismaPromise<GetPacientePrevendaAggregateType<T>>

  /**
   * Group by PacientePrevenda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacientePrevendaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PacientePrevendaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PacientePrevendaGroupByArgs['orderBy'] }
      : { orderBy?: PacientePrevendaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PacientePrevendaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPacientePrevendaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PacientePrevenda model
 */
readonly fields: PacientePrevendaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PacientePrevenda.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PacientePrevendaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PacientePrevenda model
 */
export interface PacientePrevendaFieldRefs {
  readonly id: Prisma.FieldRef<"PacientePrevenda", 'Int'>
  readonly nome: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly telefone: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly mensagem: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly genero: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly idade: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly desafio: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly energia: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly compromisso: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly sessionId: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly quizStartedAt: Prisma.FieldRef<"PacientePrevenda", 'DateTime'>
  readonly quizCompletedAt: Prisma.FieldRef<"PacientePrevenda", 'DateTime'>
  readonly userAgent: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly origem: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly pagina: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly status: Prisma.FieldRef<"PacientePrevenda", 'String'>
  readonly createdAt: Prisma.FieldRef<"PacientePrevenda", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PacientePrevenda", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PacientePrevenda findUnique
 */
export type PacientePrevendaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * Filter, which PacientePrevenda to fetch.
   */
  where: Prisma.PacientePrevendaWhereUniqueInput
}

/**
 * PacientePrevenda findUniqueOrThrow
 */
export type PacientePrevendaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * Filter, which PacientePrevenda to fetch.
   */
  where: Prisma.PacientePrevendaWhereUniqueInput
}

/**
 * PacientePrevenda findFirst
 */
export type PacientePrevendaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * Filter, which PacientePrevenda to fetch.
   */
  where?: Prisma.PacientePrevendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacientePrevendas to fetch.
   */
  orderBy?: Prisma.PacientePrevendaOrderByWithRelationInput | Prisma.PacientePrevendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PacientePrevendas.
   */
  cursor?: Prisma.PacientePrevendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacientePrevendas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacientePrevendas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PacientePrevendas.
   */
  distinct?: Prisma.PacientePrevendaScalarFieldEnum | Prisma.PacientePrevendaScalarFieldEnum[]
}

/**
 * PacientePrevenda findFirstOrThrow
 */
export type PacientePrevendaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * Filter, which PacientePrevenda to fetch.
   */
  where?: Prisma.PacientePrevendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacientePrevendas to fetch.
   */
  orderBy?: Prisma.PacientePrevendaOrderByWithRelationInput | Prisma.PacientePrevendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PacientePrevendas.
   */
  cursor?: Prisma.PacientePrevendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacientePrevendas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacientePrevendas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PacientePrevendas.
   */
  distinct?: Prisma.PacientePrevendaScalarFieldEnum | Prisma.PacientePrevendaScalarFieldEnum[]
}

/**
 * PacientePrevenda findMany
 */
export type PacientePrevendaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * Filter, which PacientePrevendas to fetch.
   */
  where?: Prisma.PacientePrevendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacientePrevendas to fetch.
   */
  orderBy?: Prisma.PacientePrevendaOrderByWithRelationInput | Prisma.PacientePrevendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PacientePrevendas.
   */
  cursor?: Prisma.PacientePrevendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacientePrevendas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacientePrevendas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PacientePrevendas.
   */
  distinct?: Prisma.PacientePrevendaScalarFieldEnum | Prisma.PacientePrevendaScalarFieldEnum[]
}

/**
 * PacientePrevenda create
 */
export type PacientePrevendaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * The data needed to create a PacientePrevenda.
   */
  data: Prisma.XOR<Prisma.PacientePrevendaCreateInput, Prisma.PacientePrevendaUncheckedCreateInput>
}

/**
 * PacientePrevenda createMany
 */
export type PacientePrevendaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PacientePrevendas.
   */
  data: Prisma.PacientePrevendaCreateManyInput | Prisma.PacientePrevendaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PacientePrevenda createManyAndReturn
 */
export type PacientePrevendaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * The data used to create many PacientePrevendas.
   */
  data: Prisma.PacientePrevendaCreateManyInput | Prisma.PacientePrevendaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PacientePrevenda update
 */
export type PacientePrevendaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * The data needed to update a PacientePrevenda.
   */
  data: Prisma.XOR<Prisma.PacientePrevendaUpdateInput, Prisma.PacientePrevendaUncheckedUpdateInput>
  /**
   * Choose, which PacientePrevenda to update.
   */
  where: Prisma.PacientePrevendaWhereUniqueInput
}

/**
 * PacientePrevenda updateMany
 */
export type PacientePrevendaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PacientePrevendas.
   */
  data: Prisma.XOR<Prisma.PacientePrevendaUpdateManyMutationInput, Prisma.PacientePrevendaUncheckedUpdateManyInput>
  /**
   * Filter which PacientePrevendas to update
   */
  where?: Prisma.PacientePrevendaWhereInput
  /**
   * Limit how many PacientePrevendas to update.
   */
  limit?: number
}

/**
 * PacientePrevenda updateManyAndReturn
 */
export type PacientePrevendaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * The data used to update PacientePrevendas.
   */
  data: Prisma.XOR<Prisma.PacientePrevendaUpdateManyMutationInput, Prisma.PacientePrevendaUncheckedUpdateManyInput>
  /**
   * Filter which PacientePrevendas to update
   */
  where?: Prisma.PacientePrevendaWhereInput
  /**
   * Limit how many PacientePrevendas to update.
   */
  limit?: number
}

/**
 * PacientePrevenda upsert
 */
export type PacientePrevendaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * The filter to search for the PacientePrevenda to update in case it exists.
   */
  where: Prisma.PacientePrevendaWhereUniqueInput
  /**
   * In case the PacientePrevenda found by the `where` argument doesn't exist, create a new PacientePrevenda with this data.
   */
  create: Prisma.XOR<Prisma.PacientePrevendaCreateInput, Prisma.PacientePrevendaUncheckedCreateInput>
  /**
   * In case the PacientePrevenda was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PacientePrevendaUpdateInput, Prisma.PacientePrevendaUncheckedUpdateInput>
}

/**
 * PacientePrevenda delete
 */
export type PacientePrevendaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
  /**
   * Filter which PacientePrevenda to delete.
   */
  where: Prisma.PacientePrevendaWhereUniqueInput
}

/**
 * PacientePrevenda deleteMany
 */
export type PacientePrevendaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PacientePrevendas to delete
   */
  where?: Prisma.PacientePrevendaWhereInput
  /**
   * Limit how many PacientePrevendas to delete.
   */
  limit?: number
}

/**
 * PacientePrevenda without action
 */
export type PacientePrevendaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacientePrevenda
   */
  select?: Prisma.PacientePrevendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacientePrevenda
   */
  omit?: Prisma.PacientePrevendaOmit<ExtArgs> | null
}
