
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PacienteTPM` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PacienteTPM
 * 
 */
export type PacienteTPMModel = runtime.Types.Result.DefaultSelection<Prisma.$PacienteTPMPayload>

export type AggregatePacienteTPM = {
  _count: PacienteTPMCountAggregateOutputType | null
  _avg: PacienteTPMAvgAggregateOutputType | null
  _sum: PacienteTPMSumAggregateOutputType | null
  _min: PacienteTPMMinAggregateOutputType | null
  _max: PacienteTPMMaxAggregateOutputType | null
}

export type PacienteTPMAvgAggregateOutputType = {
  id: number | null
}

export type PacienteTPMSumAggregateOutputType = {
  id: number | null
}

export type PacienteTPMMinAggregateOutputType = {
  id: number | null
  nome: string | null
  telefone: string | null
  email: string | null
  mensagem: string | null
  faseTpm: string | null
  compulsao: string | null
  alimentacao: string | null
  emocional: string | null
  objetivo: string | null
  sessionId: string | null
  quizStartedAt: Date | null
  quizCompletedAt: Date | null
  userAgent: string | null
  origem: string | null
  pagina: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PacienteTPMMaxAggregateOutputType = {
  id: number | null
  nome: string | null
  telefone: string | null
  email: string | null
  mensagem: string | null
  faseTpm: string | null
  compulsao: string | null
  alimentacao: string | null
  emocional: string | null
  objetivo: string | null
  sessionId: string | null
  quizStartedAt: Date | null
  quizCompletedAt: Date | null
  userAgent: string | null
  origem: string | null
  pagina: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PacienteTPMCountAggregateOutputType = {
  id: number
  nome: number
  telefone: number
  email: number
  mensagem: number
  faseTpm: number
  compulsao: number
  alimentacao: number
  emocional: number
  objetivo: number
  sessionId: number
  quizStartedAt: number
  quizCompletedAt: number
  userAgent: number
  origem: number
  pagina: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PacienteTPMAvgAggregateInputType = {
  id?: true
}

export type PacienteTPMSumAggregateInputType = {
  id?: true
}

export type PacienteTPMMinAggregateInputType = {
  id?: true
  nome?: true
  telefone?: true
  email?: true
  mensagem?: true
  faseTpm?: true
  compulsao?: true
  alimentacao?: true
  emocional?: true
  objetivo?: true
  sessionId?: true
  quizStartedAt?: true
  quizCompletedAt?: true
  userAgent?: true
  origem?: true
  pagina?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PacienteTPMMaxAggregateInputType = {
  id?: true
  nome?: true
  telefone?: true
  email?: true
  mensagem?: true
  faseTpm?: true
  compulsao?: true
  alimentacao?: true
  emocional?: true
  objetivo?: true
  sessionId?: true
  quizStartedAt?: true
  quizCompletedAt?: true
  userAgent?: true
  origem?: true
  pagina?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PacienteTPMCountAggregateInputType = {
  id?: true
  nome?: true
  telefone?: true
  email?: true
  mensagem?: true
  faseTpm?: true
  compulsao?: true
  alimentacao?: true
  emocional?: true
  objetivo?: true
  sessionId?: true
  quizStartedAt?: true
  quizCompletedAt?: true
  userAgent?: true
  origem?: true
  pagina?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PacienteTPMAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PacienteTPM to aggregate.
   */
  where?: Prisma.PacienteTPMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacienteTPMS to fetch.
   */
  orderBy?: Prisma.PacienteTPMOrderByWithRelationInput | Prisma.PacienteTPMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PacienteTPMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacienteTPMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacienteTPMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PacienteTPMS
  **/
  _count?: true | PacienteTPMCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PacienteTPMAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PacienteTPMSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PacienteTPMMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PacienteTPMMaxAggregateInputType
}

export type GetPacienteTPMAggregateType<T extends PacienteTPMAggregateArgs> = {
      [P in keyof T & keyof AggregatePacienteTPM]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePacienteTPM[P]>
    : Prisma.GetScalarType<T[P], AggregatePacienteTPM[P]>
}




export type PacienteTPMGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PacienteTPMWhereInput
  orderBy?: Prisma.PacienteTPMOrderByWithAggregationInput | Prisma.PacienteTPMOrderByWithAggregationInput[]
  by: Prisma.PacienteTPMScalarFieldEnum[] | Prisma.PacienteTPMScalarFieldEnum
  having?: Prisma.PacienteTPMScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PacienteTPMCountAggregateInputType | true
  _avg?: PacienteTPMAvgAggregateInputType
  _sum?: PacienteTPMSumAggregateInputType
  _min?: PacienteTPMMinAggregateInputType
  _max?: PacienteTPMMaxAggregateInputType
}

export type PacienteTPMGroupByOutputType = {
  id: number
  nome: string
  telefone: string
  email: string | null
  mensagem: string | null
  faseTpm: string | null
  compulsao: string | null
  alimentacao: string | null
  emocional: string | null
  objetivo: string | null
  sessionId: string | null
  quizStartedAt: Date | null
  quizCompletedAt: Date | null
  userAgent: string | null
  origem: string | null
  pagina: string | null
  status: string
  createdAt: Date
  updatedAt: Date
  _count: PacienteTPMCountAggregateOutputType | null
  _avg: PacienteTPMAvgAggregateOutputType | null
  _sum: PacienteTPMSumAggregateOutputType | null
  _min: PacienteTPMMinAggregateOutputType | null
  _max: PacienteTPMMaxAggregateOutputType | null
}

export type GetPacienteTPMGroupByPayload<T extends PacienteTPMGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PacienteTPMGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PacienteTPMGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PacienteTPMGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PacienteTPMGroupByOutputType[P]>
      }
    >
  >



export type PacienteTPMWhereInput = {
  AND?: Prisma.PacienteTPMWhereInput | Prisma.PacienteTPMWhereInput[]
  OR?: Prisma.PacienteTPMWhereInput[]
  NOT?: Prisma.PacienteTPMWhereInput | Prisma.PacienteTPMWhereInput[]
  id?: Prisma.IntFilter<"PacienteTPM"> | number
  nome?: Prisma.StringFilter<"PacienteTPM"> | string
  telefone?: Prisma.StringFilter<"PacienteTPM"> | string
  email?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  mensagem?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  faseTpm?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  compulsao?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  alimentacao?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  emocional?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  objetivo?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  sessionId?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  quizStartedAt?: Prisma.DateTimeNullableFilter<"PacienteTPM"> | Date | string | null
  quizCompletedAt?: Prisma.DateTimeNullableFilter<"PacienteTPM"> | Date | string | null
  userAgent?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  origem?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  pagina?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  status?: Prisma.StringFilter<"PacienteTPM"> | string
  createdAt?: Prisma.DateTimeFilter<"PacienteTPM"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PacienteTPM"> | Date | string
}

export type PacienteTPMOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  mensagem?: Prisma.SortOrderInput | Prisma.SortOrder
  faseTpm?: Prisma.SortOrderInput | Prisma.SortOrder
  compulsao?: Prisma.SortOrderInput | Prisma.SortOrder
  alimentacao?: Prisma.SortOrderInput | Prisma.SortOrder
  emocional?: Prisma.SortOrderInput | Prisma.SortOrder
  objetivo?: Prisma.SortOrderInput | Prisma.SortOrder
  sessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  origem?: Prisma.SortOrderInput | Prisma.SortOrder
  pagina?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacienteTPMWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PacienteTPMWhereInput | Prisma.PacienteTPMWhereInput[]
  OR?: Prisma.PacienteTPMWhereInput[]
  NOT?: Prisma.PacienteTPMWhereInput | Prisma.PacienteTPMWhereInput[]
  nome?: Prisma.StringFilter<"PacienteTPM"> | string
  telefone?: Prisma.StringFilter<"PacienteTPM"> | string
  email?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  mensagem?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  faseTpm?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  compulsao?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  alimentacao?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  emocional?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  objetivo?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  sessionId?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  quizStartedAt?: Prisma.DateTimeNullableFilter<"PacienteTPM"> | Date | string | null
  quizCompletedAt?: Prisma.DateTimeNullableFilter<"PacienteTPM"> | Date | string | null
  userAgent?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  origem?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  pagina?: Prisma.StringNullableFilter<"PacienteTPM"> | string | null
  status?: Prisma.StringFilter<"PacienteTPM"> | string
  createdAt?: Prisma.DateTimeFilter<"PacienteTPM"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PacienteTPM"> | Date | string
}, "id">

export type PacienteTPMOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  mensagem?: Prisma.SortOrderInput | Prisma.SortOrder
  faseTpm?: Prisma.SortOrderInput | Prisma.SortOrder
  compulsao?: Prisma.SortOrderInput | Prisma.SortOrder
  alimentacao?: Prisma.SortOrderInput | Prisma.SortOrder
  emocional?: Prisma.SortOrderInput | Prisma.SortOrder
  objetivo?: Prisma.SortOrderInput | Prisma.SortOrder
  sessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  origem?: Prisma.SortOrderInput | Prisma.SortOrder
  pagina?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PacienteTPMCountOrderByAggregateInput
  _avg?: Prisma.PacienteTPMAvgOrderByAggregateInput
  _max?: Prisma.PacienteTPMMaxOrderByAggregateInput
  _min?: Prisma.PacienteTPMMinOrderByAggregateInput
  _sum?: Prisma.PacienteTPMSumOrderByAggregateInput
}

export type PacienteTPMScalarWhereWithAggregatesInput = {
  AND?: Prisma.PacienteTPMScalarWhereWithAggregatesInput | Prisma.PacienteTPMScalarWhereWithAggregatesInput[]
  OR?: Prisma.PacienteTPMScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PacienteTPMScalarWhereWithAggregatesInput | Prisma.PacienteTPMScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PacienteTPM"> | number
  nome?: Prisma.StringWithAggregatesFilter<"PacienteTPM"> | string
  telefone?: Prisma.StringWithAggregatesFilter<"PacienteTPM"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  mensagem?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  faseTpm?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  compulsao?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  alimentacao?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  emocional?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  objetivo?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  sessionId?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  quizStartedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PacienteTPM"> | Date | string | null
  quizCompletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PacienteTPM"> | Date | string | null
  userAgent?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  origem?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  pagina?: Prisma.StringNullableWithAggregatesFilter<"PacienteTPM"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"PacienteTPM"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PacienteTPM"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PacienteTPM"> | Date | string
}

export type PacienteTPMCreateInput = {
  nome: string
  telefone: string
  email?: string | null
  mensagem?: string | null
  faseTpm?: string | null
  compulsao?: string | null
  alimentacao?: string | null
  emocional?: string | null
  objetivo?: string | null
  sessionId?: string | null
  quizStartedAt?: Date | string | null
  quizCompletedAt?: Date | string | null
  userAgent?: string | null
  origem?: string | null
  pagina?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PacienteTPMUncheckedCreateInput = {
  id?: number
  nome: string
  telefone: string
  email?: string | null
  mensagem?: string | null
  faseTpm?: string | null
  compulsao?: string | null
  alimentacao?: string | null
  emocional?: string | null
  objetivo?: string | null
  sessionId?: string | null
  quizStartedAt?: Date | string | null
  quizCompletedAt?: Date | string | null
  userAgent?: string | null
  origem?: string | null
  pagina?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PacienteTPMUpdateInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  faseTpm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  compulsao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alimentacao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emocional?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objetivo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacienteTPMUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  faseTpm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  compulsao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alimentacao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emocional?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objetivo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacienteTPMCreateManyInput = {
  id?: number
  nome: string
  telefone: string
  email?: string | null
  mensagem?: string | null
  faseTpm?: string | null
  compulsao?: string | null
  alimentacao?: string | null
  emocional?: string | null
  objetivo?: string | null
  sessionId?: string | null
  quizStartedAt?: Date | string | null
  quizCompletedAt?: Date | string | null
  userAgent?: string | null
  origem?: string | null
  pagina?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PacienteTPMUpdateManyMutationInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  faseTpm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  compulsao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alimentacao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emocional?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objetivo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacienteTPMUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mensagem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  faseTpm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  compulsao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alimentacao?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emocional?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  objetivo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quizStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizCompletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origem?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pagina?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacienteTPMCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  faseTpm?: Prisma.SortOrder
  compulsao?: Prisma.SortOrder
  alimentacao?: Prisma.SortOrder
  emocional?: Prisma.SortOrder
  objetivo?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origem?: Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacienteTPMAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PacienteTPMMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  faseTpm?: Prisma.SortOrder
  compulsao?: Prisma.SortOrder
  alimentacao?: Prisma.SortOrder
  emocional?: Prisma.SortOrder
  objetivo?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origem?: Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacienteTPMMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  faseTpm?: Prisma.SortOrder
  compulsao?: Prisma.SortOrder
  alimentacao?: Prisma.SortOrder
  emocional?: Prisma.SortOrder
  objetivo?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  quizStartedAt?: Prisma.SortOrder
  quizCompletedAt?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origem?: Prisma.SortOrder
  pagina?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacienteTPMSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type PacienteTPMSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  telefone?: boolean
  email?: boolean
  mensagem?: boolean
  faseTpm?: boolean
  compulsao?: boolean
  alimentacao?: boolean
  emocional?: boolean
  objetivo?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["pacienteTPM"]>

export type PacienteTPMSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  telefone?: boolean
  email?: boolean
  mensagem?: boolean
  faseTpm?: boolean
  compulsao?: boolean
  alimentacao?: boolean
  emocional?: boolean
  objetivo?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["pacienteTPM"]>

export type PacienteTPMSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  telefone?: boolean
  email?: boolean
  mensagem?: boolean
  faseTpm?: boolean
  compulsao?: boolean
  alimentacao?: boolean
  emocional?: boolean
  objetivo?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["pacienteTPM"]>

export type PacienteTPMSelectScalar = {
  id?: boolean
  nome?: boolean
  telefone?: boolean
  email?: boolean
  mensagem?: boolean
  faseTpm?: boolean
  compulsao?: boolean
  alimentacao?: boolean
  emocional?: boolean
  objetivo?: boolean
  sessionId?: boolean
  quizStartedAt?: boolean
  quizCompletedAt?: boolean
  userAgent?: boolean
  origem?: boolean
  pagina?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PacienteTPMOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "telefone" | "email" | "mensagem" | "faseTpm" | "compulsao" | "alimentacao" | "emocional" | "objetivo" | "sessionId" | "quizStartedAt" | "quizCompletedAt" | "userAgent" | "origem" | "pagina" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["pacienteTPM"]>

export type $PacienteTPMPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PacienteTPM"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nome: string
    telefone: string
    email: string | null
    mensagem: string | null
    faseTpm: string | null
    compulsao: string | null
    alimentacao: string | null
    emocional: string | null
    objetivo: string | null
    sessionId: string | null
    quizStartedAt: Date | null
    quizCompletedAt: Date | null
    userAgent: string | null
    origem: string | null
    pagina: string | null
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pacienteTPM"]>
  composites: {}
}

export type PacienteTPMGetPayload<S extends boolean | null | undefined | PacienteTPMDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload, S>

export type PacienteTPMCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PacienteTPMFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PacienteTPMCountAggregateInputType | true
  }

export interface PacienteTPMDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PacienteTPM'], meta: { name: 'PacienteTPM' } }
  /**
   * Find zero or one PacienteTPM that matches the filter.
   * @param {PacienteTPMFindUniqueArgs} args - Arguments to find a PacienteTPM
   * @example
   * // Get one PacienteTPM
   * const pacienteTPM = await prisma.pacienteTPM.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PacienteTPMFindUniqueArgs>(args: Prisma.SelectSubset<T, PacienteTPMFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PacienteTPM that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PacienteTPMFindUniqueOrThrowArgs} args - Arguments to find a PacienteTPM
   * @example
   * // Get one PacienteTPM
   * const pacienteTPM = await prisma.pacienteTPM.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PacienteTPMFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PacienteTPMFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PacienteTPM that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteTPMFindFirstArgs} args - Arguments to find a PacienteTPM
   * @example
   * // Get one PacienteTPM
   * const pacienteTPM = await prisma.pacienteTPM.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PacienteTPMFindFirstArgs>(args?: Prisma.SelectSubset<T, PacienteTPMFindFirstArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PacienteTPM that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteTPMFindFirstOrThrowArgs} args - Arguments to find a PacienteTPM
   * @example
   * // Get one PacienteTPM
   * const pacienteTPM = await prisma.pacienteTPM.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PacienteTPMFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PacienteTPMFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PacienteTPMS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteTPMFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PacienteTPMS
   * const pacienteTPMS = await prisma.pacienteTPM.findMany()
   * 
   * // Get first 10 PacienteTPMS
   * const pacienteTPMS = await prisma.pacienteTPM.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pacienteTPMWithIdOnly = await prisma.pacienteTPM.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PacienteTPMFindManyArgs>(args?: Prisma.SelectSubset<T, PacienteTPMFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PacienteTPM.
   * @param {PacienteTPMCreateArgs} args - Arguments to create a PacienteTPM.
   * @example
   * // Create one PacienteTPM
   * const PacienteTPM = await prisma.pacienteTPM.create({
   *   data: {
   *     // ... data to create a PacienteTPM
   *   }
   * })
   * 
   */
  create<T extends PacienteTPMCreateArgs>(args: Prisma.SelectSubset<T, PacienteTPMCreateArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PacienteTPMS.
   * @param {PacienteTPMCreateManyArgs} args - Arguments to create many PacienteTPMS.
   * @example
   * // Create many PacienteTPMS
   * const pacienteTPM = await prisma.pacienteTPM.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PacienteTPMCreateManyArgs>(args?: Prisma.SelectSubset<T, PacienteTPMCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PacienteTPMS and returns the data saved in the database.
   * @param {PacienteTPMCreateManyAndReturnArgs} args - Arguments to create many PacienteTPMS.
   * @example
   * // Create many PacienteTPMS
   * const pacienteTPM = await prisma.pacienteTPM.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PacienteTPMS and only return the `id`
   * const pacienteTPMWithIdOnly = await prisma.pacienteTPM.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PacienteTPMCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PacienteTPMCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PacienteTPM.
   * @param {PacienteTPMDeleteArgs} args - Arguments to delete one PacienteTPM.
   * @example
   * // Delete one PacienteTPM
   * const PacienteTPM = await prisma.pacienteTPM.delete({
   *   where: {
   *     // ... filter to delete one PacienteTPM
   *   }
   * })
   * 
   */
  delete<T extends PacienteTPMDeleteArgs>(args: Prisma.SelectSubset<T, PacienteTPMDeleteArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PacienteTPM.
   * @param {PacienteTPMUpdateArgs} args - Arguments to update one PacienteTPM.
   * @example
   * // Update one PacienteTPM
   * const pacienteTPM = await prisma.pacienteTPM.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PacienteTPMUpdateArgs>(args: Prisma.SelectSubset<T, PacienteTPMUpdateArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PacienteTPMS.
   * @param {PacienteTPMDeleteManyArgs} args - Arguments to filter PacienteTPMS to delete.
   * @example
   * // Delete a few PacienteTPMS
   * const { count } = await prisma.pacienteTPM.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PacienteTPMDeleteManyArgs>(args?: Prisma.SelectSubset<T, PacienteTPMDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PacienteTPMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteTPMUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PacienteTPMS
   * const pacienteTPM = await prisma.pacienteTPM.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PacienteTPMUpdateManyArgs>(args: Prisma.SelectSubset<T, PacienteTPMUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PacienteTPMS and returns the data updated in the database.
   * @param {PacienteTPMUpdateManyAndReturnArgs} args - Arguments to update many PacienteTPMS.
   * @example
   * // Update many PacienteTPMS
   * const pacienteTPM = await prisma.pacienteTPM.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PacienteTPMS and only return the `id`
   * const pacienteTPMWithIdOnly = await prisma.pacienteTPM.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PacienteTPMUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PacienteTPMUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PacienteTPM.
   * @param {PacienteTPMUpsertArgs} args - Arguments to update or create a PacienteTPM.
   * @example
   * // Update or create a PacienteTPM
   * const pacienteTPM = await prisma.pacienteTPM.upsert({
   *   create: {
   *     // ... data to create a PacienteTPM
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PacienteTPM we want to update
   *   }
   * })
   */
  upsert<T extends PacienteTPMUpsertArgs>(args: Prisma.SelectSubset<T, PacienteTPMUpsertArgs<ExtArgs>>): Prisma.Prisma__PacienteTPMClient<runtime.Types.Result.GetResult<Prisma.$PacienteTPMPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PacienteTPMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteTPMCountArgs} args - Arguments to filter PacienteTPMS to count.
   * @example
   * // Count the number of PacienteTPMS
   * const count = await prisma.pacienteTPM.count({
   *   where: {
   *     // ... the filter for the PacienteTPMS we want to count
   *   }
   * })
  **/
  count<T extends PacienteTPMCountArgs>(
    args?: Prisma.Subset<T, PacienteTPMCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PacienteTPMCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PacienteTPM.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteTPMAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PacienteTPMAggregateArgs>(args: Prisma.Subset<T, PacienteTPMAggregateArgs>): Prisma.PrismaPromise<GetPacienteTPMAggregateType<T>>

  /**
   * Group by PacienteTPM.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteTPMGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PacienteTPMGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PacienteTPMGroupByArgs['orderBy'] }
      : { orderBy?: PacienteTPMGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PacienteTPMGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPacienteTPMGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PacienteTPM model
 */
readonly fields: PacienteTPMFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PacienteTPM.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PacienteTPMClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PacienteTPM model
 */
export interface PacienteTPMFieldRefs {
  readonly id: Prisma.FieldRef<"PacienteTPM", 'Int'>
  readonly nome: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly telefone: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly email: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly mensagem: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly faseTpm: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly compulsao: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly alimentacao: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly emocional: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly objetivo: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly sessionId: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly quizStartedAt: Prisma.FieldRef<"PacienteTPM", 'DateTime'>
  readonly quizCompletedAt: Prisma.FieldRef<"PacienteTPM", 'DateTime'>
  readonly userAgent: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly origem: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly pagina: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly status: Prisma.FieldRef<"PacienteTPM", 'String'>
  readonly createdAt: Prisma.FieldRef<"PacienteTPM", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PacienteTPM", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PacienteTPM findUnique
 */
export type PacienteTPMFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * Filter, which PacienteTPM to fetch.
   */
  where: Prisma.PacienteTPMWhereUniqueInput
}

/**
 * PacienteTPM findUniqueOrThrow
 */
export type PacienteTPMFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * Filter, which PacienteTPM to fetch.
   */
  where: Prisma.PacienteTPMWhereUniqueInput
}

/**
 * PacienteTPM findFirst
 */
export type PacienteTPMFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * Filter, which PacienteTPM to fetch.
   */
  where?: Prisma.PacienteTPMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacienteTPMS to fetch.
   */
  orderBy?: Prisma.PacienteTPMOrderByWithRelationInput | Prisma.PacienteTPMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PacienteTPMS.
   */
  cursor?: Prisma.PacienteTPMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacienteTPMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacienteTPMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PacienteTPMS.
   */
  distinct?: Prisma.PacienteTPMScalarFieldEnum | Prisma.PacienteTPMScalarFieldEnum[]
}

/**
 * PacienteTPM findFirstOrThrow
 */
export type PacienteTPMFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * Filter, which PacienteTPM to fetch.
   */
  where?: Prisma.PacienteTPMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacienteTPMS to fetch.
   */
  orderBy?: Prisma.PacienteTPMOrderByWithRelationInput | Prisma.PacienteTPMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PacienteTPMS.
   */
  cursor?: Prisma.PacienteTPMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacienteTPMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacienteTPMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PacienteTPMS.
   */
  distinct?: Prisma.PacienteTPMScalarFieldEnum | Prisma.PacienteTPMScalarFieldEnum[]
}

/**
 * PacienteTPM findMany
 */
export type PacienteTPMFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * Filter, which PacienteTPMS to fetch.
   */
  where?: Prisma.PacienteTPMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PacienteTPMS to fetch.
   */
  orderBy?: Prisma.PacienteTPMOrderByWithRelationInput | Prisma.PacienteTPMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PacienteTPMS.
   */
  cursor?: Prisma.PacienteTPMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PacienteTPMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PacienteTPMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PacienteTPMS.
   */
  distinct?: Prisma.PacienteTPMScalarFieldEnum | Prisma.PacienteTPMScalarFieldEnum[]
}

/**
 * PacienteTPM create
 */
export type PacienteTPMCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * The data needed to create a PacienteTPM.
   */
  data: Prisma.XOR<Prisma.PacienteTPMCreateInput, Prisma.PacienteTPMUncheckedCreateInput>
}

/**
 * PacienteTPM createMany
 */
export type PacienteTPMCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PacienteTPMS.
   */
  data: Prisma.PacienteTPMCreateManyInput | Prisma.PacienteTPMCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PacienteTPM createManyAndReturn
 */
export type PacienteTPMCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * The data used to create many PacienteTPMS.
   */
  data: Prisma.PacienteTPMCreateManyInput | Prisma.PacienteTPMCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PacienteTPM update
 */
export type PacienteTPMUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * The data needed to update a PacienteTPM.
   */
  data: Prisma.XOR<Prisma.PacienteTPMUpdateInput, Prisma.PacienteTPMUncheckedUpdateInput>
  /**
   * Choose, which PacienteTPM to update.
   */
  where: Prisma.PacienteTPMWhereUniqueInput
}

/**
 * PacienteTPM updateMany
 */
export type PacienteTPMUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PacienteTPMS.
   */
  data: Prisma.XOR<Prisma.PacienteTPMUpdateManyMutationInput, Prisma.PacienteTPMUncheckedUpdateManyInput>
  /**
   * Filter which PacienteTPMS to update
   */
  where?: Prisma.PacienteTPMWhereInput
  /**
   * Limit how many PacienteTPMS to update.
   */
  limit?: number
}

/**
 * PacienteTPM updateManyAndReturn
 */
export type PacienteTPMUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * The data used to update PacienteTPMS.
   */
  data: Prisma.XOR<Prisma.PacienteTPMUpdateManyMutationInput, Prisma.PacienteTPMUncheckedUpdateManyInput>
  /**
   * Filter which PacienteTPMS to update
   */
  where?: Prisma.PacienteTPMWhereInput
  /**
   * Limit how many PacienteTPMS to update.
   */
  limit?: number
}

/**
 * PacienteTPM upsert
 */
export type PacienteTPMUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * The filter to search for the PacienteTPM to update in case it exists.
   */
  where: Prisma.PacienteTPMWhereUniqueInput
  /**
   * In case the PacienteTPM found by the `where` argument doesn't exist, create a new PacienteTPM with this data.
   */
  create: Prisma.XOR<Prisma.PacienteTPMCreateInput, Prisma.PacienteTPMUncheckedCreateInput>
  /**
   * In case the PacienteTPM was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PacienteTPMUpdateInput, Prisma.PacienteTPMUncheckedUpdateInput>
}

/**
 * PacienteTPM delete
 */
export type PacienteTPMDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
  /**
   * Filter which PacienteTPM to delete.
   */
  where: Prisma.PacienteTPMWhereUniqueInput
}

/**
 * PacienteTPM deleteMany
 */
export type PacienteTPMDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PacienteTPMS to delete
   */
  where?: Prisma.PacienteTPMWhereInput
  /**
   * Limit how many PacienteTPMS to delete.
   */
  limit?: number
}

/**
 * PacienteTPM without action
 */
export type PacienteTPMDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteTPM
   */
  select?: Prisma.PacienteTPMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PacienteTPM
   */
  omit?: Prisma.PacienteTPMOmit<ExtArgs> | null
}
